#!/bin/sh

set -e

# == CONFIGURATION ==

RESTIC=/usr/bin/restic
#export RESTIC_REPOSITORY="sftp://backup-xpected@heimdal/writable/bench2"
export RESTIC_REPOSITORY="/tmp/restic-bench5"
TEST_FROM="/tmp/fromdir"
LOGFILE="timing_$(date "+%Y%m%d_%H%M%S").log"

echo "Using command '${RESTIC}'."

# == CLEANUP ==

rm -rf "${TEST_FROM}"

# == SETUP: fromdir ==

mkdir "${TEST_FROM}"
for i in $(seq 10)
do
    DSTFILE="$(mktemp "${TEST_FROM}"/important_file_XXXXXXX.txt)"
    shuf -n3 <<EOF > "${DSTFILE}"
Hello, World!
foobar
Not something very interesting.
Hello!
Yes, hello?
Who is there?
Surely, you can't be serious!
I am serious.
And stop calling me Shirly!
This is a self-descriptive line.
Lorem ipsum
Dolor sit something something.
The quick brown fox.
Jumped over by the lazy dogs.
This sentence is an anagram for itself.
EOF
    DSTFILE="$(mktemp "${TEST_FROM}"/important_data_XXXXXXX.dat)"
    dd if=/dev/urandom of="${DSTFILE}" bs=8M count=1 2> /dev/null
done

# == SETUP: destdir ==

export RESTIC_PASSWORD="1234"
${RESTIC} init

# == EXECUTE ==

${RESTIC} version | tee "${LOGFILE}"

ITERATIONS=1000
for i in $(seq ${ITERATIONS})
do
    echo "Iteration $i / ${ITERATIONS}"
    date | tee "${TEST_FROM}/date.txt"
    ${RESTIC} snapshots --json > "${TEST_FROM}/snapshots.txt"
    ${RESTIC} backup "${TEST_FROM}" > /dev/null
    /usr/bin/time restic check
done 2>&1 | tee -a "${LOGFILE}"

echo "Results have been copied to: ${LOGFILE}"
